# Generated by Django 5.2 on 2025-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, unique=True)),
                ('password', models.CharField(blank=True, default='', help_text='Hashed password; use set_password() to assign.', max_length=128)),
                ('name', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
