# Generated by Django 5.2 on 2025-04-27 00:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(default='', help_text='Hashed password; use set_password() to assign.', max_length=128)),
                ('display_name', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to=accounts.models.profile_pic_upload_to)),
            ],
            options={
                'db_table': 'accounts_user_profile',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
