# Generated by Django 5.2 on 2025-04-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='completed_subtasks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
