# Generated by Django 5.2 on 2025-04-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_node_completed_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='missed_subtasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='ongoing_subtasks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
