# Generated by Django 5.2 on 2025-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_node_missed_subtasks_node_ongoing_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='icon',
            field=models.CharField(default='📝', max_length=10),
        ),
    ]
